services:
  # vue-app:
  #   build:
  #     context: vue-frontend
  #   ports:
  #     - "8081:8080"
  nextjs:
    build:
      context: nextjs-frontend
    ports:
      - "5000:5000" # Map the container's port to the host
    volumes:
      - ./nextjs-frontend:/app # Mount the source code for hot reloading
      - nextjs_node_modules:/app/node_modules  # Use a named volume for node_modules

    environment:
      - NODE_ENV=development # Set the environment variable
      - PORT=5000 # Set the port for Next.js
  rails-app:
    build:
      context: rails-api
    volumes:
      - ./rails-api:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/my_database
    depends_on:
      - db
      - meilisearch
    command: >
      sh -c "rm -f /app/tmp/pids/server.pid && rails db:migrate && rails db:setup  && rails server -b 0.0.0.0"
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
  meilisearch:
    image: getmeili/meilisearch:v1.12
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: 'your_master_key' # for production, this will be different

volumes:
  pg_data:
  nextjs_node_modules:
