services:
  # vue-app:
  #   build:
  #     context: vue-frontend
  #   ports:
  #     - "8081:8080"
  rails-app:
    build:
      context: rails-api
    volumes:
      - ./rails-api:/app # Ensure this path is correct
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/my_database
    depends_on:
      - db
    command: >
      sh -c "rm -f /app/tmp/pids/server.pid && rails db:migrate && rails db:setup && rails server -b 0.0.0.0"
  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"

volumes:
  pg_data:
