default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@db:5432/my_database" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@db:5432/my_database_test" } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@db:5432/my_database" } %>
